spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:init.sql
    #data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:testdb
    username: user
    password: password
  application:
    name: goliuxue
profiles:
  active: dev

server:
  port: 8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl